function [K1_nn,K2_nn,K3_nn,K4_nn] = Kupfull(dtn, N1,N2,N3,N4,r1star,r2star,r3star,r4star,r12star,r34star,F1,F2,F3,F4,U1_n,U2_n,U3_n,U4_n,U1star,U2star,U3star,U4star,B12_n,B34_n,B12starmatcT,B34starmatcT,Btil12,Btil34)

 K1_nn = sylvesterf( (speye(N1)-dtn*F1), ...
        -dtn*( kron( B34starmatcT'*kron( speye(r4star)     , U3star'*F3'*U3star )*B34starmatcT,speye(r2star)     ) +...
               kron( B34starmatcT'*kron( speye(r4star)     , speye(r3star)      )*B34starmatcT,U2star'*F2*U2star ) +...
               kron( B34starmatcT'*kron( U4star'*F4'*U4star, speye(r3star)      )*B34starmatcT,speye(r2star)     )), ...
               U1_n * tens2mat(Btil12,1) * kron( tens2mat(B34_n,3)*kron(U4_n'*U4star,U3_n'*U3star)*B34starmatcT, U2_n'*U2star)  );
        
 K2_nn = sylvesterf( (speye(N2)-dtn*F2), ...
        -dtn*( kron( B34starmatcT'*kron( speye(r4star)     , U3star'*F3'*U3star )*B34starmatcT,speye(r1star)     ) +...
               kron( B34starmatcT'*kron( speye(r4star)     , speye(r3star)      )*B34starmatcT,U1star'*F1*U1star ) +...
               kron( B34starmatcT'*kron( U4star'*F4'*U4star, speye(r3star)      )*B34starmatcT,speye(r1star)     )), ...
               U2_n * tens2mat(Btil12,2) * kron( tens2mat(B34_n,3)*kron(U4_n'*U4star,U3_n'*U3star)*B34starmatcT, U1_n'*U1star)  );
                                                     
 K3_nn = sylvesterf( (speye(N3)-dtn*F3), ...
        -dtn*( kron( B12starmatcT'*kron( speye(r2star)     , U1star'*F1'*U1star )*B12starmatcT,speye(r4star)     ) +...
               kron( B12starmatcT'*kron( speye(r2star)     , speye(r1star)      )*B12starmatcT,U4star'*F4*U4star ) +...
               kron( B12starmatcT'*kron( U2star'*F2'*U2star, speye(r1star)      )*B12starmatcT,speye(r4star)     )),...
               U3_n * tens2mat(Btil34,1) * kron( tens2mat(B12_n,3)*kron(U2_n'*U2star,U1_n'*U1star)*B12starmatcT, U4_n'*U4star)  );

 K4_nn = sylvesterf( (speye(N4)-dtn*F4), ...
        -dtn*( kron( B12starmatcT'*kron( speye(r2star)     , U1star'*F1'*U1star )*B12starmatcT,speye(r4star)     ) +...
               kron( B12starmatcT'*kron( speye(r2star)     , speye(r1star)      )*B12starmatcT,U3star'*F3*U3star ) +...
               kron( B12starmatcT'*kron( U2star'*F2'*U2star, speye(r1star)      )*B12starmatcT,speye(r4star)      )),...
               U4_n * tens2mat(Btil34,2) * kron( tens2mat(B12_n,3)*kron(U2_n'*U2star,U1_n'*U1star)*B12starmatcT, U3_n'*U3star)  );

end